apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    name: prom-grafana

---

apiVersion: v1
kind: ResourceQuota
metadata:
  name: ns-limits
  namespace: monitoring
  labels:
    name: resquota-ns
spec:
  hard:
    pods: "20"
    requests.cpu: "500m"
    requests.memory: "500Mi"
    limits.cpu: "1.8"
    limits.memory: "1.8Gi"
---

apiVersion: v1
kind: LimitRange
metadata:
  name: default-res-for-cont
  namespace: monitoring
spec:
  limits:
  - type: Container
    default:
      cpu: "100m"
      memory: "250Mi"
    defaultRequest:
      cpu: "20m"
      memory: "100Mi"

