name: Docker Image CI
on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'README.md'
jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write   # needed to push to ghcr.io

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker image
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/snakegame:latest
          docker build . -f Dockerfile -t $IMAGE_NAME
      - name: Trivy Action
        uses: lazy-actions/gitrivy@v3
        with:
         image: $IMAGE_NAME

      - name: Push image to GHCR
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/snakegame:latest
          docker push $IMAGE_NAME
